const STRINGS = {
  appName: 'E-commerce',
  splash: {
    con: `Receive everything at your doorstep.`,
  },
  onBoard: {
    screenOne: 'Choose Item',
    screenOneDes: 'Search and browse the product you want to buy at Mogo',
    next: 'Skip',
    get: 'Get Started',
    screenSecond: 'Add to Cart and Pay',
    screenSecondDes:
      'Add the product to shopping cart, choose delivery and they pay with your preferance payment',
    screenThree: 'Delivery',
    screenThreeDes:
      'Wait until the product that has been purchased comes to the house',
  },
  login: {
    title: 'Let’s Get Started!',
    con: 'fill the form to continue.',
    email: 'Email/Phone',
    password: 'Password',
    resetPass: 'Reset Password',
    terms: 'By Signing up, you agree to the ',
    services: 'Terms of Service',
    and: ' and',
    policy: ' Privacy Policy',
    logIn: 'Log in',
    haveAcc: 'Not Have an Account? ',
    in: 'Sign Up',
  },
  signUp: {
    con: 'Sign up with Social of fill the form to continue.',
    name: 'Name',
    phone: 'Phone',
    email: 'Email',
    password: 'Password',
    in: 'Log in',
    signUp: 'SignUp',
    des: 'At least 8 characters, 1 uppercase letter, 1 number, 1 symbol',
  },
  forgetPassword: {
    title: 'Forgot your password?',
    con: 'If you need help resetting your password we can help by sending you a link to reset it.',
    search: ' Your Phone Number',
    next: 'Next',
  },
  verification: {
    title: 'Phone Verification',
    con: 'Please enter the 4-digit code send to you at',
    number: '+91  12345 67890',
    resend: 'Resend Code',
    btn: 'Reset password',
  },
  changePass: {
    title: 'Change Password',
    password: 'Password',
    newPassword: 'New Password',
    confrimPass: 'Confirm Password',
    submit: 'Submit',
  },
  home: {
    title: 'Home',
    subtitle: 'lekki phase 1, Estate',
    menu: 'Menu',
    all: 'View all',
    menuOne: 'Camera',
    menuTwo: 'Food',
    menuThree: 'Hand phone',
    menuFour: 'Gamming',
    menuFive: 'Fashion',
    menuSix: 'Health Care',
    menuSeven: 'Computer',
    menuEight: 'Equipment',
    menuNine: 'Otomotif',
    menuTen: 'Sport',
    menuEleven: 'Ticket Cinema',
    menuTevel: 'Book',
    promo: 'Week Promotion mogo',
    dis: 'Discount 10%',
    start: 'Start From 50$',
    category: 'Category',
    fashionMan: 'Fashion Man',
    smartPhone: 'Smart Phone',
    fashionGirl: 'Fashion Girl',
    recomend: 'Recomended',
    productOneName: 'Nike Air Max 270 React ENG',
    productOnePrice: '$299,43',
    sale: '932 Sale',
    productTwoName: 'Nike Air Max 270 React ENG',
    productTwoPrice: '$299,43',
    productThreeName: 'Nike Air Max 270 React ENG',
    productThreePrice: '$50,00',
    productFourName: 'Nike Air Max 270 React ENG',
    productFourPrice: '$29,43',
    sale: '932 Sale',
  },
  menu: {
    title: 'Menu',
  },
  notification: {
    title: 'Notification',
    notificationOne: 'Your order is confirm, check a your order status.',
    timeOne: '9.24 Am',
    notificationTwo: 'Justas Galaburda6:30 AM, Yesterday6:30 AM, Yesterday',
    timeTwo: '10.00 pm',
    notificationThree: 'Eric Holfman2 hrs ago2 hrs ago',
    timeThree: '12.20 Am',
    notificationFour: 'Justas Galaburda5 hrs ago5 hrs ago',
    timeFour: '2.00 pm',
    notificationFive: 'Eric Holfman10 hrs ago10 hrs ago',
    timeFive: '3.00 Am',
    notificationSix: 'Charles Patterson12 hrs ago12 hrs ago',
    timeSix: '5.00 pm',
  },
  subMenu: {
    title: 'Camera',
    camera: 'Camera Digital',
    sub: 'Sub Category',
    dis: 'Item Discount',
    itemDisOne: 'Action Camera HDR',
    itemDisTwo: 'Compact Camera High...',
    itemOnePrice: '$200,00',
    itemTwoPrice: '$299,43',
    sale: '932 Sale',
    popular: 'Item Popular',
    newItem: 'New Item',
  },
  subCategory: {
    title: 'Sub Category',
  },
  subMenuAction: {
    title: 'Action',
    modalTitle: 'Filter & Sorting',
    price: 'Price',
    priceOne: '$ 50.000',
    priceTwo: '$ 100.000',
    brand: 'Brand',
    brandOne: 'Nike',
    brandTwo: 'Korea',
    brandThree: 'Mentli',
    brandFour: 'Sony',
    brandFive: 'Prada',
    brandSix: 'Samsung ',
    brandSeven: 'Supreme',
    reviews: 'Customer Reviews',
    up: '& Up',
    sortBy: 'Sort by',
    byOne: 'Price: Low to High',
    byTwo: 'Featured',
    byThree: 'Price: High to Low',
    byFour: 'Avg. Customer Review',
    byFive: 'Newest Arrivals',
    reset: 'Reset',
    apply: 'Apply',
  },
  recomended: {
    title: 'Recomended',
  },
  weekPromotion: {
    title: 'Week Promotion mogo',
    featuredPro: 'Featured Product',
  },
  homeCategory: {
    title: 'Fashion Man',
    style: 'Man Style',
  },
  productDetails: {
    title: 'Product Detail',
    name: 'Mentli Solid Blue Sliim Fit',
    color: 'COLOR',
    size: 'SIZE',
    description: 'Description',
    con: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the indu strys standard dummy text ever since the 1500s, whe an unknown printer took a galley of type and sc rambled it to make a type printer took a...',
    con1: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    con2: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the indu strys standard dummy text ever since the 1500s, whe an unknown.',
    viewMore: 'View More',
    reviewProduct: 'Review Product',
    review: '(5 Review)',
    rent: '4.5',
    personName: 'John Doe',
    date: 'December 10, 2022',
    reviewCon:
      'air max are always very comfortable fit, clean and just perfect in every way. just the box was too small and scrunched the sneakers up a little bit,',
    reachedPro: 'Top Rated Products',
    pay: 'Pay',
  },
  review: {
    title: 'Reviews',
    reviewProduct: 'Review Product',
  },
  updateReview: {
    title: 'Add a Written Review',
    think: 'So what do you think?',
    rateProduct: 'your overall rating of this product',
    submit: 'Submit',
  },
  drawer: {
    name: 'John Doe',
    email: 'Johndoe@gmail.com',
    logOut: 'Log Out',
  },
  productDetailModal: {
    saveAdd: 'Saved Address',
    addNewAdd: 'Add New Address',
    homeAddress: 'Home Address',
    name: 'John Doe',
    number: '+91 12345 67890',
    address:
      'Building No,66, 78th Main Road, 100ft Road, Indiranagar, Bangalore 123456',
    ofcAddress: 'Office Address',
    confirmAddress: 'Confirm Address',
  },
  addAddress: {
    title: 'Add Address',
    fullName: 'Full Name',
    address: 'Address',
    zipCode: 'Zipcode',
    country: 'Country',
    city: 'City',
    district: 'District',
    homeAddress: 'Home Address',
    ofcAddress: 'Office Address',
    save: 'Save Address',
  },
  details: {
    title: 'Details',
    deliveryAdd: 'Delivery Address',
    change: 'Change',
    address:
      'Building No,66, 78th Main Road, 100ft Road, Indiranagar, Bangalore 123456 Mobile: 98765 43210',
    paymentDetails: 'Payment Details',
    subTotal: 'Subtotal:',
    taxes: 'Taxes:',
    subTotalRu: '$2,850.00',
    taxesRu: '$40.00',
    total: 'Total',
    totalRu: '$2,890.00',
    continue: 'Continue to Payment',
  },
  payment: {
    title: 'Payment',
    chooseMethod: 'Choose your payment method',
    creditCard: 'Credit / Debit Card',
    cash: 'Cash On Delivery',
    payPal: 'Paypal',
    wallet: 'Google Wallet',
    addCard: '+ Add New Card',
    pay: 'Pay',
    yuppy: 'Yuppy!!',
    seller: 'Your Payment Recive to Seller',
  },
  addCard: {
    cardNo: 'Card Number',
    exDate: 'Expiration Date',
    securityCode: 'Security Code',
    cardHolder: 'Card Holder',
    save: 'Save',
  },
  search: {
    recent: 'RECENT',
    actionCamera: 'Action Camera',
    cable: 'Cable',
    macBook: 'Macbook',
    featuredProduct: 'Featured Product',
  },
  catBrand: {
    title: 'Category Brand',
    name: 'Nike Sport',
    dataName: 'Nike Sport Shoes Man...',
    price: '$100,00',
    sale: '932 Sale',
  },
  cart: {
    title: 'Cart',
    pay: 'PAY',
  },
  flashSale: {
    title: 'Flash Sale',
    end: 'End in',
    time: '  23:24:05',
  },
  flashProductDetail: {
    title: 'Product Detail',
    sale: 'Flash Sale',
    available: '9 Available',
    camera: 'Compact Camera High...',
    price: '$299,43',
    checkPrice: '$250,00',
    detailPro: 'Detail Product',
    name1: '(1) - MackBook Pro ',
    name2: '(2) - SSD 256 GB',
    name3: '(3) Ram 8 GB DDR4',
    name4: '(4) Non Touch Bar',
    top: 'Top Rated Products',
  },
  lorem: {
    lorem1:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the indu strys standard dummy text ever since the 1500s, whe an unknown printer took a galley of type and sc rambled it to make a type',
    lorem2:
      'Ipsum has been the indu strys standard dummy text ever since the 1500s, whe an unknown printerto ok a galley of type and sc rambled it to make a type',
  },
  aboutUs: {
    title: 'About us',
  },
  setting: {
    title: 'Setting',
    darkTheme: 'Dark Theme',
    orderNotification: 'Order Notifications',
    discountNotification: 'Discount Notifications',
    promotionNotification: 'Promotion notification',
    account: 'Account',
    address: 'Address',
    paymentMethod: 'Payment Method',
    privacyPolicy: 'Privacy policy',
    terms: 'Terms & conditions',
  },
  saveAddress: {
    title: 'Saved Addresses',
  },
  cardDetails: {
    title: 'Card Details',
    number: '**** **** **** 3947',
  },
  language: {
    title: 'Language',
    eng: 'English',
    arabic: 'Arabic',
    chinese: 'Chinese',
    hindi: 'Hindi',
    indo: 'Indonesia',
  },
  order: {
    title: 'My Order',
    deliver: 'Delivered',
    process: 'Processing',
    cancel: 'Canceled',
    orderId: 'Order Id: 5t36-9iu2',
    date: 'Wed, 12 Sep',
    qty: 'Quantity:',
    qtyItem: ' 03',
    totalAmount: 'Total Amount: ',
    totalAmountValue: '$2,890',
    detail: 'Detail',
    deliver: 'Delivered',
  },
  trackOrder: {
    title: 'Track My Order',
    orderId: 'Order Id: 5t36-9iu2',
    date: 'Wed, 12 Sep',
    amt: 'Amt:',
    amtRu: '2,890.00',
    eta: 'ETA: 15 Min',
    orderPlaced: 'Order Placed',
    receiveOrder: 'We have received your order',
    timeOne: '10:04',
    paymentCon: 'Payment Confirmed',
    waiting: 'Awaiting confirmation...',
    timeTwo: ' 10:06',
    orderProcess: 'Order Processed',
    prepare: 'We are preparing your order.',
    timeThree: ' 10:08',
    pickUp: 'Ready to Pickup',
    shop: ' Order from SpingoShop',
    timeFour: '11:00',
    add: 'House No: 1234, 2nd Floor Sector 18, Silicon valey USA.',
    otherAdd: 'Home, Work & Other Address',
    deliveryAdd: 'Delivery Address',
  },
  profile: {
    title: 'My Profile',
    fullName: 'Full Name',
    email: 'Email Address',
    number: 'Phone Number',
    password: 'Password',
    change: 'Change',
    update: 'Update',
  },
};
export default STRINGS;
